package com.ideu.demo.server08.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "orders")
public class Order {
    @Id


    private String id;

    @Column(name = "user_id")
    private Long userId;

    @Column(name = "type")
    private String type;


    @Column(name = "detail_id")
    private String detailId;

    @Column(name = "price")
    private String price;

    @Column(name = "description")
    private String description;

    @Column(name = "contact_phone")
    private String contactPhone;

    @Column(name = "user_address")
    private String userAddress;

    @Column(name = "completion_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime completionTime;

    @Column(name = "area")
    private String area;

    @Column(name = "order_status")
    private String orderStatus;

    @Column(name = "priority")
    private String priority;

    @Column(name = "assigned_engineer")
    private Long assignedEngineer;

    @Column(name = "created_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdTime;

    @Column(name = "updated_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedTime;


    @Column(name = "finish_pic")
    private String finishPic;

    BigDecimal balance;
    // Getters and setters (generated by Lombok's @Data)


}
