spring:
  application:
    name: server08
  datasource:
    url: jdbc:mysql://106.3.99.64:20021/tjpu22s08?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: tjpu22s08
    password: tjpu22s08
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
#      host: 106.3.99.64
      host: localhost
#      port: 20022
      port: 6379
#      password: 91ieduroot
      database: 8
      timeout:  3000
server:
  port: 8080
sa-token:
  token-name: tjpu22s08
  timeout: 2592000
  active-timeout: -1
  is-log: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iedu.demo.server08.entity

upload:
  minio:
    endpoint: 106.3.99.64
    port: 20028
    accessKey: tjpu22s08
    secretKey: tjpu22s08
    bucketName: tjpu22s08
    secure: false
    expire: 3600
